### ISSUE TITLE
Callback results in error

### ISSUE THREAD

**Issue by runegronkjaer** [vendrcontrib/vendr-payment-provider-quickpay#4]
When QuickPay callback it must be doing so more than one time. The order will get the correct callback, which does not fail. So actually everything is fine with the order being updated and the payment has been made.

BUT. Each order also results in an error message in the log stating that the "QuickPay-Checksum-Sha256" header is missing. So the callback must be made twice for some reason and one of them without the header.

If it matters until now we have only tried it with MobilePay orders.

The expected behavior would be that there would be no error for each order as it's quite misleading.

**Comment by bjarnef** [comment]
Hi @runegronkjaer 

Yes, I believe the callback is request twice - once when when Vendr continue/redirect to confirmation page and when QuickPay send the POST request back to the callback.

@mattbrailsford I guess it would also hit this method when Vendr request the callback method?
https://github.com/vendrcontrib/vendr-payment-provider-quickpay/blob/v2/dev/src/Vendr.Contrib.PaymentProviders.QuickPay/QuickPayCheckoutPaymentProvider.cs#L423

**Comment by mattbrailsford** [comment]
If this payment provider finalizes as a result of a webhook callback then you need to set `FinalizeOnContinueUrl` to false https://github.com/vendrcontrib/vendr-payment-provider-quickpay/blob/v2/dev/src/Vendr.Contrib.PaymentProviders.QuickPay/QuickPayCheckoutPaymentProvider.cs#L33 as wit this set, it means the callback handler will be called when you move to the `continue` page as well (which you only really want to happen for payment providers that finalize orders as part of the redirect back to the site)

This will be why you are seeing multiple calls to the callback and why one will be failing.

**Comment by bjarnef** [comment]
@mattbrailsford I think it originally used the same approach as DIBS D2. QuickPay doesn't use webhooks, but they do try up til 10 times with a POST to callback method.

https://github.com/vendrhub/vendr-payment-provider-dibs/commit/12ae315a794f43d04d3fe001bbec436f8e038c20#diff-067c978bc568248cbea023ce02afb21334704ba67dc202f784da4d11316bab85R20

However it seems it was later changed to `FinalizeAtContinueUrl = false`, so it seems I may have missed that part..
https://github.com/vendrhub/vendr-payment-provider-dibs/blob/v2/dev/src/Vendr.PaymentProviders.Dibs/DibsPaymentProvider.cs#L33

**Comment by bjarnef** [comment]
Should be fixed in v1.1.1 and v2.0.1 on NuGet: https://www.nuget.org/packages/Vendr.Contrib.PaymentProviders.QuickPay
